#ifndef PASCAL_PARSER_TOKENS_H
#define PASCAL_PARSER_TOKENS_H

enum token_enum {
    PROGRAM_TOKEN,
    CONST_TOKEN,
    VAR_TOKEN,
    BEGIN_TOKEN,
    END_TOKEN,
    IF_TOKEN,
    THEN_TOKEN,
    WHILE_TOKEN,
    DO_TOKEN,
    READ_TOKEN,
    WRITE_TOKEN,
    ID_TOKEN,
    NUM_TOKEN,
    SC_TOKEN,
    PT_TOKEN,
    PLUS_TOKEN,
    MINUS_TOKEN,
    MULTI_TOKEN,
    DIV_TOKEN,
    COM_TOKEN,
    ASSIGN_TOKEN,
    LOWER_TOKEN,
    LOWER_OR_EQUAL_TOKEN,
    GREATER_TOKEN,
    GREATER_OR_EQUAL_TOKEN,
    EQUAL_TOKEN,
    NOT_EQUAL_TOKEN,
    OP_TOKEN,
    CP_TOKEN,
    EOF_TOKEN,
    ERROR_TOKEN
}current_token;

static char *tokens[] = {
        "PROGRAM_TOKEN",
        "CONST_TOKEN",
        "VAR_TOKEN",
        "BEGIN_TOKEN",
        "END_TOKEN",
        "IF_TOKEN",
        "THEN_TOKEN",
        "WHILE_TOKEN",
        "DO_TOKEN",
        "READ_TOKEN",
        "WRITE_TOKEN",
        "ID_TOKEN",
        "NUM_TOKEN",
        "SC_TOKEN",
        "PT_TOKEN",
        "PLUS_TOKEN",
        "MINUS_TOKEN",
        "MULTI_TOKEN",
        "DIV_TOKEN",
        "COM_TOKEN",
        "ASSIGN_TOKEN",
        "LOWER_TOKEN",
        "LOWER_OR_EQUAL_TOKEN",
        "GREATER_TOKEN",
        "GREATER_OR_EQUAL_TOKEN",
        "EQUAL_TOKEN",
        "NOT_EQUAL_TOKEN",
        "OP_TOKEN",
        "CP_TOKEN",
        "EOF_TOKEN",
        "ERROR_TOKEN"
};
#endif //PASCAL_PARSER_TOKENS_H
